<a href="https://colab.research.google.com/github/iamjaykumar/pandas_project/blob/main/pandas_project%26advanced_concept.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv")

In [ ]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [ ]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [ ]:
df[['Name','Sex','Ticket','Cabin','Embarked']]

,Name,Sex,Ticket,Cabin,Embarked
0,"Braund, Mr. Owen Harris",male,A/5 21171,NaN,S
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,PC 17599,C85,C
2,"Heikkinen, Miss. Laina",female,STON/O2. 3101282,NaN,S
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,113803,C123,S
4,"Allen, Mr. William Henry",male,373450,NaN,S
...,...,...,...,...,...
886,"Montvila, Rev. Juozas",male,211536,NaN,S
887,"Graham, Miss. Margaret Edith",female,112053,B42,S
888,"Johnston, Miss. Catherine Helen ""Carrie""",female,W./C. 6607,NaN,S
889,"Behr, Mr. Karl Howell",male,111369,C148,C
890,"Dooley, Mr. Patrick",male,370376,NaN,Q

In [ ]:
# filtering data
df.dtypes == 'object'

PassengerId    False
Survived       False
Pclass         False
Name            True
Sex             True
Age            False
SibSp          False
Parch          False
Ticket          True
Fare           False
Cabin           True
Embarked        True
dtype: bool

In [ ]:
df.dtypes[df.dtypes == 'object'] # provide you only object column

Name        object
Sex         object
Ticket      object
Cabin       object
Embarked    object
dtype: object

In [ ]:
df[df.dtypes[df.dtypes=='object'].index] # it filter and provide you the object data only.

,Name,Sex,Ticket,Cabin,Embarked
0,"Braund, Mr. Owen Harris",male,A/5 21171,NaN,S
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,PC 17599,C85,C
2,"Heikkinen, Miss. Laina",female,STON/O2. 3101282,NaN,S
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,113803,C123,S
4,"Allen, Mr. William Henry",male,373450,NaN,S
...,...,...,...,...,...
886,"Montvila, Rev. Juozas",male,211536,NaN,S
887,"Graham, Miss. Margaret Edith",female,112053,B42,S
888,"Johnston, Miss. Catherine Helen ""Carrie""",female,W./C. 6607,NaN,S
889,"Behr, Mr. Karl Howell",male,111369,C148,C
890,"Dooley, Mr. Patrick",male,370376,NaN,Q

In [ ]:
type(df.dtypes[df.dtypes=='object'])

pandas.core.series.Series

In [ ]:
df[df.dtypes[df.dtypes == 'object'].index].describe()

                       Name   Sex  Ticket Cabin Embarked
count                   891   891     891   204      889
unique                  891     2     681   147        3
top     Dooley, Mr. Patrick  male  347082    G6        S
freq                      1   577       7     4      644

In [ ]:
#now it's time to filter the data of float type
df[df.dtypes[df.dtypes == 'float64'].index]

      Age     Fare
0    22.0   7.2500
1    38.0  71.2833
2    26.0   7.9250
3    35.0  53.1000
4    35.0   8.0500
..    ...      ...
886  27.0  13.0000
887  19.0  30.0000
888   NaN  23.4500
889  26.0  30.0000
890  32.0   7.7500

[891 rows x 2 columns]

In [ ]:
df[df.dtypes[df.dtypes == 'float64'].index].describe()

              Age        Fare
count  714.000000  891.000000
mean    29.699118   32.204208
std     14.526497   49.693429
min      0.420000    0.000000
25%     20.125000    7.910400
50%     28.000000   14.454200
75%     38.000000   31.000000
max     80.000000  512.329200

In [ ]:
df[df.dtypes[df.dtypes == 'int'].index].describe()

       PassengerId    Survived      Pclass       SibSp       Parch
count   891.000000  891.000000  891.000000  891.000000  891.000000
mean    446.000000    0.383838    2.308642    0.523008    0.381594
std     257.353842    0.486592    0.836071    1.102743    0.806057
min       1.000000    0.000000    1.000000    0.000000    0.000000
25%     223.500000    0.000000    2.000000    0.000000    0.000000
50%     446.000000    0.000000    3.000000    0.000000    0.000000
75%     668.500000    1.000000    3.000000    1.000000    0.000000
max     891.000000    1.000000    3.000000    8.000000    6.000000

In [ ]:
df[['Ticket','Cabin']][4:11:2]

     Ticket Cabin
4    373450   NaN
6     17463   E46
8    347742   NaN
10  PP 9549    G6

In [ ]:
df['new_col'] = 0 # creating new column
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,new_col
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,0
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,0
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,0
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,0
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,0
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,0
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,0

In [ ]:
df['new_col'] = df["PassengerId"] + df['Pclass']
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,new_col
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,4
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,3
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,6
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,5
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,889
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,889
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,892
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,891
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,894

In [ ]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,new_col
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,4
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,3
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,6
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,5
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,8

In [ ]:
pd.Categorical(df['Pclass'])

[3, 1, 3, 1, 3, ..., 2, 1, 3, 1, 3]
Length: 891
Categories (3, int64): [1, 2, 3]

In [ ]:
pd.Categorical(df['Pclass']).describe()

            counts     freqs
categories
1              216  0.242424
2              184  0.206510
3              491  0.551066

In [ ]:
pd.Categorical(df['Survived'])

[0, 1, 1, 1, 0, ..., 0, 1, 0, 1, 0]
Length: 891
Categories (2, int64): [0, 1]

In [ ]:
df['Cabin'].unique()

array([nan, 'C85', 'C123', 'E46', 'G6', 'C103', 'D56', 'A6',
       'C23 C25 C27', 'B78', 'D33', 'B30', 'C52', 'B28', 'C83', 'F33',
       'F G73', 'E31', 'A5', 'D10 D12', 'D26', 'C110', 'B58 B60', 'E101',
       'F E69', 'D47', 'B86', 'F2', 'C2', 'E33', 'B19', 'A7', 'C49', 'F4',
       'A32', 'B4', 'B80', 'A31', 'D36', 'D15', 'C93', 'C78', 'D35',
       'C87', 'B77', 'E67', 'B94', 'C125', 'C99', 'C118', 'D7', 'A19',
       'B49', 'D', 'C22 C26', 'C106', 'C65', 'E36', 'C54',
       'B57 B59 B63 B66', 'C7', 'E34', 'C32', 'B18', 'C124', 'C91', 'E40',
       'T', 'C128', 'D37', 'B35', 'E50', 'C82', 'B96 B98', 'E10', 'E44',
       'A34', 'C104', 'C111', 'C92', 'E38', 'D21', 'E12', 'E63', 'A14',
       'B37', 'C30', 'D20', 'B79', 'E25', 'D46', 'B73', 'C95', 'B38',
       'B39', 'B22', 'C86', 'C70', 'A16', 'C101', 'C68', 'A10', 'E68',
       'B41', 'A20', 'D19', 'D50', 'D9', 'A23', 'B50', 'A26', 'D48',
       'E58', 'C126', 'B71', 'B51 B53 B55', 'D49', 'B5', 'B20', 'F G63',
       'C62 C64', 'E24', 'C90', 'C45', 'E8', 'B101', 'D45', 'C46', 'D30',
       'E121', 'D11', 'E77', 'F38', 'B3', 'D6', 'B82 B84', 'D17', 'A36',
       'B102', 'B69', 'E49', 'C47', 'D28', 'E17', 'A24', 'C50', 'B42',
       'C148'], dtype=object)

In [ ]:
df[df['Age']>18] #filter 18+ data

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,new_col
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S,11
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C,12
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S,14
14,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.0,0,0,350406,7.8542,NaN,S,18
16,17,0,3,"Rice, Master. Eugene",male,2.0,4,1,382652,29.1250,NaN,Q,20
...,...,...,...,...,...,...,...,...,...,...,...,...,...
850,851,0,3,"Andersson, Master. Sigvard Harald Elias",male,4.0,4,2,347082,31.2750,NaN,S,854
852,853,0,3,"Boulos, Miss. Nourelain",female,9.0,1,1,2678,15.2458,NaN,C,856
853,854,1,1,"Lines, Miss. Mary Conover",female,16.0,0,1,PC 17592,39.4000,D28,S,855
869,870,1,3,"Johnson, Master. Harold Theodor",male,4.0,1,1,347742,11.1333,NaN,S,873
875,876,1,3,"Najib, Miss. Adele Kiamie ""Jane""",female,15.0,0,0,2667,7.2250,NaN,C,879

In [ ]:
 df[df['Fare']> 32.204200 ]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,new_col
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,3
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,5
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S,8
23,24,1,1,"Sloper, Mr. William Thompson",male,28.0,0,0,113788,35.5000,A6,S,25
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19.0,3,2,19950,263.0000,C23 C25 C27,S,29
...,...,...,...,...,...,...,...,...,...,...,...,...,...
856,857,1,1,"Wick, Mrs. George Dennick (Mary Hitchcock)",female,45.0,1,1,36928,164.8667,NaN,S,858
863,864,0,3,"Sage, Miss. Dorothy Edith ""Dolly""",female,NaN,8,2,CA. 2343,69.5500,NaN,S,867
867,868,0,1,"Roebling, Mr. Washington Augustus II",male,31.0,0,0,PC 17590,50.4958,A24,S,869
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S,873
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C,881

In [ ]:
 df[df['Fare']==0]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,new_col
179,180,0,3,"Leonard, Mr. Lionel",male,36.0,0,0,LINE,0.0,NaN,S,183
263,264,0,1,"Harrison, Mr. William",male,40.0,0,0,112059,0.0,B94,S,265
271,272,1,3,"Tornquist, Mr. William Henry",male,25.0,0,0,LINE,0.0,NaN,S,275
277,278,0,2,"Parkes, Mr. Francis ""Frank""",male,NaN,0,0,239853,0.0,NaN,S,280
302,303,0,3,"Johnson, Mr. William Cahoone Jr",male,19.0,0,0,LINE,0.0,NaN,S,306
413,414,0,2,"Cunningham, Mr. Alfred Fleming",male,NaN,0,0,239853,0.0,NaN,S,416
466,467,0,2,"Campbell, Mr. William",male,NaN,0,0,239853,0.0,NaN,S,469
481,482,0,2,"Frost, Mr. Anthony Wood ""Archie""",male,NaN,0,0,239854,0.0,NaN,S,484
597,598,0,3,"Johnson, Mr. Alfred",male,49.0,0,0,LINE,0.0,NaN,S,601
633,634,0,1,"Parr, Mr. William Henry Marsh",male,NaN,0,0,112052,0.0,NaN,S,635
674,675,0,2,"Watson, Mr. Ennis Hastings",male,NaN,0,0,239856,0.0,NaN,S,677
732,733,0,2,"Knight, Mr. Robert J",male,NaN,0,0,239855,0.0,NaN,S,735
806,807,0,1,"Andrews, Mr. Thomas Jr",male,39.0,0,0,112050,0.0,A36,S,808
815,816,0,1,"Fry, Mr. Richard",male,NaN,0,0,112058,0.0,B102,S,817
822,823,0,1,"Reuchlin, Jonkheer. John George",male,38.0,0,0,19972,0.0,NaN,S,824

In [ ]:
df[df['Sex']=='male']

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,new_col
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,4
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,8
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q,9
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S,8
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...
883,884,0,2,"Banfield, Mr. Frederick James",male,28.0,0,0,C.A./SOTON 34068,10.5000,NaN,S,886
884,885,0,3,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,7.0500,NaN,S,888
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,889
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,891
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,894

In [ ]:
df[df['Pclass']==1]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,new_col
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,3
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,5
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S,8
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S,13
23,24,1,1,"Sloper, Mr. William Thompson",male,28.0,0,0,113788,35.5000,A6,S,25
...,...,...,...,...,...,...,...,...,...,...,...,...,...
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S,873
872,873,0,1,"Carlsson, Mr. Frans Olof",male,33.0,0,0,695,5.0000,B51 B53 B55,S,874
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C,881
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,889
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,891

In [ ]:
df[df['Survived']==1]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,new_col
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,3
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,6
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,5
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S,12
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...
875,876,1,3,"Najib, Miss. Adele Kiamie ""Jane""",female,15.0,0,0,2667,7.2250,NaN,C,879
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C,881
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,NaN,S,883
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,889
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,891

In [ ]:
df[(df['Sex']=='female') & (df['Fare']> 32)]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,new_col
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,3
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,5
31,32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,NaN,1,0,PC 17569,146.5208,B78,C,33
43,44,1,2,"Laroche, Miss. Simonne Marie Anne Andree",female,3.0,1,2,SC/Paris 2123,41.5792,NaN,C,46
52,53,1,1,"Harper, Mrs. Henry Sleeper (Myna Haxtun)",female,49.0,1,0,PC 17572,76.7292,D33,C,54
...,...,...,...,...,...,...,...,...,...,...,...,...,...
853,854,1,1,"Lines, Miss. Mary Conover",female,16.0,0,1,PC 17592,39.4000,D28,S,855
856,857,1,1,"Wick, Mrs. George Dennick (Mary Hitchcock)",female,45.0,1,1,36928,164.8667,NaN,S,858
863,864,0,3,"Sage, Miss. Dorothy Edith ""Dolly""",female,NaN,8,2,CA. 2343,69.5500,NaN,S,867
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S,873
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C,881

In [ ]:
survivide_female = df[(df['Survived'] ==1) & (df['Sex'] == 'female')]
total_female = len(survivide_female)
print(total_female)

233

In [ ]:
survivide_
male = df[(df['Survived'] ==1) & (df['Sex'] == 'male')]
total_male = len(survivide_male)
print(total_male)

109

In [ ]:
survived_total = df[df['Survived'] == 1]
print(len(survived_total))

342

In [ ]:
survived_total = df[df['Survived'] == 0]
print(len(survived_total))

549

In [ ]:
df[df['Fare'] == max(df['Fare'])]['Name']

258                      Ward, Miss. Anna
679    Cardeza, Mr. Thomas Drake Martinez
737                Lesurer, Mr. Gustave J
Name: Name, dtype: object

In [ ]:
df[0:2]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,new_col
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,4
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,3

.iloc is a purely integer-location based indexing method in pandas. It is used for selection by position

In [ ]:
df.iloc[0:2,[0,1,2]]

   PassengerId  Survived  Pclass
0            1         0       3
1            2         1       1

loc = .loc is a label-based indexing method in pandas. It is used to select data by label (or index).

In [ ]:
df.loc[0:2]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,new_col
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,4
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,3
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,6

# index_changing into pandas

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv")

In [20]:
s = df['Name'][0:10]

In [21]:
s

0                              Braund, Mr. Owen Harris
1    Cumings, Mrs. John Bradley (Florence Briggs Th...
2                               Heikkinen, Miss. Laina
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                             Allen, Mr. William Henry
5                                     Moran, Mr. James
6                              McCarthy, Mr. Timothy J
7                       Palsson, Master. Gosta Leonard
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)
9                  Nasser, Mrs. Nicholas (Adele Achem)
Name: Name, dtype: object

In [22]:
type(s)
l= ['a','b','c','d','e','f','g','h','i','j']

In [23]:
l

['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

In [24]:
len(s)

10

In [25]:
# pd.Series(s,index=l)
pd.Series(list(s),index=l)

a                              Braund, Mr. Owen Harris
b    Cumings, Mrs. John Bradley (Florence Briggs Th...
c                               Heikkinen, Miss. Laina
d         Futrelle, Mrs. Jacques Heath (Lily May Peel)
e                             Allen, Mr. William Henry
f                                     Moran, Mr. James
g                              McCarthy, Mr. Timothy J
h                       Palsson, Master. Gosta Leonard
i    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)
j                  Nasser, Mrs. Nicholas (Adele Achem)
dtype: object

In [10]:
s

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object

In [11]:
s[0]

'Braund, Mr. Owen Harris'

In [12]:
pd.Series([3,4,5,6,6], index=[2,4,5,6,1])

2    3
4    4
5    5
6    6
1    6
dtype: int64

# pandas part4

In [26]:
import pandas as pd

In [27]:
df = pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv")

In [28]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [29]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [36]:
df.drop('PassengerId', axis=1, inplace=True) # remove the column

KeyError: "['PassengerId'] not found in axis"

In [37]:
df

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [38]:
df.drop(3,inplace=True)# to delete permanently we use inplace=True

In [39]:
df

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [41]:
df.set_index("Name",inplace=True)

In [42]:
df

,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
Name,,,,,,,,,,
"Braund, Mr. Owen Harris",0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S
"Cumings, Mrs. John Bradley (Florence Briggs Thayer)",1,1,female,38.0,1,0,PC 17599,71.2833,C85,C
"Heikkinen, Miss. Laina",1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
"Allen, Mr. William Henry",0,3,male,35.0,0,0,373450,8.0500,NaN,S
"Moran, Mr. James",0,3,male,NaN,0,0,330877,8.4583,NaN,Q
...,...,...,...,...,...,...,...,...,...,...
"Montvila, Rev. Juozas",0,2,male,27.0,0,0,211536,13.0000,NaN,S
"Graham, Miss. Margaret Edith",1,1,female,19.0,0,0,112053,30.0000,B42,S
"Johnston, Miss. Catherine Helen ""Carrie""",0,3,female,NaN,1,2,W./C. 6607,23.4500,NaN,S
"Behr, Mr. Karl Howell",1,1,male,26.0,0,0,111369,30.0000,C148,C
"Dooley, Mr. Patrick",0,3,male,32.0,0,0,370376,7.7500,NaN,Q

In [44]:
df.reset_index()

,Name,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,"Braund, Mr. Owen Harris",0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,1,female,38.0,1,0,PC 17599,71.2833,C85,C
2,"Heikkinen, Miss. Laina",1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,"Allen, Mr. William Henry",0,3,male,35.0,0,0,373450,8.0500,NaN,S
4,"Moran, Mr. James",0,3,male,NaN,0,0,330877,8.4583,NaN,Q
...,...,...,...,...,...,...,...,...,...,...,...
885,"Montvila, Rev. Juozas",0,2,male,27.0,0,0,211536,13.0000,NaN,S
886,"Graham, Miss. Margaret Edith",1,1,female,19.0,0,0,112053,30.0000,B42,S
887,"Johnston, Miss. Catherine Helen ""Carrie""",0,3,female,NaN,1,2,W./C. 6607,23.4500,NaN,S
888,"Behr, Mr. Karl Howell",1,1,male,26.0,0,0,111369,30.0000,C148,C
889,"Dooley, Mr. Patrick",0,3,male,32.0,0,0,370376,7.7500,NaN,Q

In [45]:
d = {
    'key1': [3,4,5,6,7],
    'key2': [5,6,7,8,9],
    'key3': [4,5,6,7,8],
}
#All list must be of the same length

In [46]:
pd.DataFrame(d)

   key1  key2  key3
0     3     5     4
1     4     6     5
2     5     7     6
3     6     8     7
4     7     9     8

In [47]:
df1 = pd.read_csv("https://gist.githubusercontent.com/JordanLyons/139e6cf1dafa0b8cb5ae32f6facef8a4/raw/6bf4a1baf7a9245cf2f0b16feefa86672bf39b19/free-taxonomy.csv")

In [48]:
df1

,name,id,parent_name,parent_id,vocabulary,x-description,x-notes,services
0,Emergency,1101,0,0.0,Open Eligibility Human Services,"Services for psychiatric emergencies, emergenc...",NaN,NaN
1,Food,1102,0,0.0,Open Eligibility Human Services,"Services for free meals, food pantries, help p...",NaN,NaN
2,Housing,1103,0,0.0,Open Eligibility Human Services,"Services for emergency, short-term and long-te...",NaN,NaN
3,Goods,1104,0,0.0,Open Eligibility Human Services,"Services for clothing, furniture, baby supplie...",NaN,NaN
4,Transit,1105,0,0.0,Open Eligibility Human Services,"Services for bus passes, transportation to sch...",NaN,NaN
...,...,...,...,...,...,...,...,...
322,In Danger,20089,Urgency,20087.0,Open Eligibility Human Situations,NaN,NaN,NaN
323,Chronic Illness,20090,Health,1106.0,Open Eligibility Human Situations,NaN,NaN,NaN
324,Spouses,20091,Role,20072.0,Open Eligibility Human Situations,NaN,NaN,NaN
325,Dependents,20092,Role,20072.0,Open Eligibility Human Situations,NaN,NaN,NaN
326,Intellectual Disability,20093,Disability,20017.0,Open Eligibility Human Situations,NaN,NaN,NaN

In [49]:
df1.dropna() # it will delete/drop row automatically which has NaN value
# It will not delete permanently. to delete permanently we use inplace=True

Empty DataFrame
Columns: [name, id, parent_name, parent_id, vocabulary, x-description, x-notes, services]
Index: []

In [52]:
df1.dropna(inplace=True)
df1

Empty DataFrame
Columns: [name, id, parent_name, parent_id, vocabulary, x-description, x-notes, services]
Index: []

In [53]:
df2 = pd.read_csv("https://gist.githubusercontent.com/JordanLyons/139e6cf1dafa0b8cb5ae32f6facef8a4/raw/6bf4a1baf7a9245cf2f0b16feefa86672bf39b19/free-taxonomy.csv")

In [54]:
df2

,name,id,parent_name,parent_id,vocabulary,x-description,x-notes,services
0,Emergency,1101,0,0.0,Open Eligibility Human Services,"Services for psychiatric emergencies, emergenc...",NaN,NaN
1,Food,1102,0,0.0,Open Eligibility Human Services,"Services for free meals, food pantries, help p...",NaN,NaN
2,Housing,1103,0,0.0,Open Eligibility Human Services,"Services for emergency, short-term and long-te...",NaN,NaN
3,Goods,1104,0,0.0,Open Eligibility Human Services,"Services for clothing, furniture, baby supplie...",NaN,NaN
4,Transit,1105,0,0.0,Open Eligibility Human Services,"Services for bus passes, transportation to sch...",NaN,NaN
...,...,...,...,...,...,...,...,...
322,In Danger,20089,Urgency,20087.0,Open Eligibility Human Situations,NaN,NaN,NaN
323,Chronic Illness,20090,Health,1106.0,Open Eligibility Human Situations,NaN,NaN,NaN
324,Spouses,20091,Role,20072.0,Open Eligibility Human Situations,NaN,NaN,NaN
325,Dependents,20092,Role,20072.0,Open Eligibility Human Situations,NaN,NaN,NaN
326,Intellectual Disability,20093,Disability,20017.0,Open Eligibility Human Situations,NaN,NaN,NaN

In [55]:
df2.dropna(axis=1) #It will delete/drop column which has NaN value

                        name     id                         vocabulary
0                  Emergency   1101    Open Eligibility Human Services
1                       Food   1102    Open Eligibility Human Services
2                    Housing   1103    Open Eligibility Human Services
3                      Goods   1104    Open Eligibility Human Services
4                    Transit   1105    Open Eligibility Human Services
..                       ...    ...                                ...
322                In Danger  20089  Open Eligibility Human Situations
323          Chronic Illness  20090  Open Eligibility Human Situations
324                  Spouses  20091  Open Eligibility Human Situations
325               Dependents  20092  Open Eligibility Human Situations
326  Intellectual Disability  20093  Open Eligibility Human Situations

[327 rows x 3 columns]

In [60]:
df2.fillna('jay' , inplace=True)

<ipython-input-60-4a31fa93c044>:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'jay' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df2.fillna('jay' , inplace=True)

In [61]:
df2.dropna()

,name,id,parent_name,parent_id,vocabulary,x-description,x-notes,services
0,Emergency,1101,0,0.0,Open Eligibility Human Services,"Services for psychiatric emergencies, emergenc...",jay,jay
1,Food,1102,0,0.0,Open Eligibility Human Services,"Services for free meals, food pantries, help p...",jay,jay
2,Housing,1103,0,0.0,Open Eligibility Human Services,"Services for emergency, short-term and long-te...",jay,jay
3,Goods,1104,0,0.0,Open Eligibility Human Services,"Services for clothing, furniture, baby supplie...",jay,jay
4,Transit,1105,0,0.0,Open Eligibility Human Services,"Services for bus passes, transportation to sch...",jay,jay
...,...,...,...,...,...,...,...,...
322,In Danger,20089,Urgency,20087.0,Open Eligibility Human Situations,jay,jay,jay
323,Chronic Illness,20090,Health,1106.0,Open Eligibility Human Situations,jay,jay,jay
324,Spouses,20091,Role,20072.0,Open Eligibility Human Situations,jay,jay,jay
325,Dependents,20092,Role,20072.0,Open Eligibility Human Situations,jay,jay,jay
326,Intellectual Disability,20093,Disability,20017.0,Open Eligibility Human Situations,jay,jay,jay

In [62]:
df2

,name,id,parent_name,parent_id,vocabulary,x-description,x-notes,services
0,Emergency,1101,0,0.0,Open Eligibility Human Services,"Services for psychiatric emergencies, emergenc...",jay,jay
1,Food,1102,0,0.0,Open Eligibility Human Services,"Services for free meals, food pantries, help p...",jay,jay
2,Housing,1103,0,0.0,Open Eligibility Human Services,"Services for emergency, short-term and long-te...",jay,jay
3,Goods,1104,0,0.0,Open Eligibility Human Services,"Services for clothing, furniture, baby supplie...",jay,jay
4,Transit,1105,0,0.0,Open Eligibility Human Services,"Services for bus passes, transportation to sch...",jay,jay
...,...,...,...,...,...,...,...,...
322,In Danger,20089,Urgency,20087.0,Open Eligibility Human Situations,jay,jay,jay
323,Chronic Illness,20090,Health,1106.0,Open Eligibility Human Situations,jay,jay,jay
324,Spouses,20091,Role,20072.0,Open Eligibility Human Situations,jay,jay,jay
325,Dependents,20092,Role,20072.0,Open Eligibility Human Situations,jay,jay,jay
326,Intellectual Disability,20093,Disability,20017.0,Open Eligibility Human Situations,jay,jay,jay

In [63]:
df3 = pd.read_csv("https://gist.githubusercontent.com/JordanLyons/139e6cf1dafa0b8cb5ae32f6facef8a4/raw/6bf4a1baf7a9245cf2f0b16feefa86672bf39b19/free-taxonomy.csv")

Now we will grouphy it means:


1.   Group 0
2.   Group 1
3.  and find mean

In [64]:
g = df.groupby('Survived')

In [65]:
g

After grouping the data, this line calculates the sum of each column within each group. For each group (survived=0 and survived=1), pandas will go through all the other columns and sum up the values for the rows belonging to that group. For example, it would sum up the ages of all passengers who did not survive, and separately sum up the ages of all passengers who survived. The result will be a new DataFrame where the index represents the Survived groups (0 and 1), and the columns represent the original columns from the Titanic dataset, with the values being the sum for each group.

In [66]:
g.sum() # group 0

,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
Survived,,,,,,,,,
0,1390,malemalemalemalemalemalemalefemalemalefemalema...,12985.50,304,181,A/5 2117137345033087717463349909A/5. 215134708...,12142.7199,E46C23 C25 C27B30C83F G73E31A5D26C110B58 B60D2...,SSQSSSSSQSSSCSSCSCSSSSSCSQCSSSCCSCSSCSSSSSCSSS...
1,666,femalefemalefemalefemalefemalefemalefemalemale...,8184.67,161,159,PC 17599STON/O2. 3101282347742237736PP 9549113...,16498.1294,C85G6C103D56A6B78D33C52B28F33C23 C25 C27D10 D1...,CSSCSSSSCSQSSQCQCCCQQCSSSSCSSSSSSQSSSCSSSQSCSC...

In [67]:
g.mean()

TypeError: agg function failed [how->mean,dtype->object]

In [69]:
g1 = df.groupby('Pclass')
g1.sum()

,Survived,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
Pclass,,,,,,,,,
1,135,femalemalefemalemalemalemalefemalemalemalefema...,7076.42,89,77,PC 175991746311378311378819950PC 17601PC 17569...,18124.3125,C85E46C103A6C23 C25 C27B78D33B30C52B28C83C23 C...,CSSSSCCCSCCSSCSSSCCSSCSSSCSCSSSCCSSCCCCCSSQSSC...
2,87,femalefemalemalemalemalemalefemalefemalefemale...,5168.83,74,70,237736248706244373239865248698C.A. 2457911668S...,3801.8417,D56F33E101F2F4F2DE101DF2F33DF33F4E101E77,CSSSSSSCSSSSSSSSSSSSCSSSCSSSSSSSCSSSSSSSSSSSSS...
3,119,malefemalemalemalemalefemalefemalemalemalefema...,8924.92,302,193,A/5 21171STON/O2. 3101282373450330877349909347...,6714.6951,G6F G73F E69G6G6G6E10F G63F G73E121F38E121,SSSQSSSSSSQSCQSSCQSQCSSCSCQSQQCSSSCSCSCSSSSCSS...

In [70]:
g1.max()

TypeError: agg function failed [how->max,dtype->object]

In [71]:
g1.max()['Fare']

TypeError: agg function failed [how->max,dtype->object]

In [72]:
df

,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
Name,,,,,,,,,,
"Braund, Mr. Owen Harris",0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S
"Cumings, Mrs. John Bradley (Florence Briggs Thayer)",1,1,female,38.0,1,0,PC 17599,71.2833,C85,C
"Heikkinen, Miss. Laina",1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
"Allen, Mr. William Henry",0,3,male,35.0,0,0,373450,8.0500,NaN,S
"Moran, Mr. James",0,3,male,NaN,0,0,330877,8.4583,NaN,Q
...,...,...,...,...,...,...,...,...,...,...
"Montvila, Rev. Juozas",0,2,male,27.0,0,0,211536,13.0000,NaN,S
"Graham, Miss. Margaret Edith",1,1,female,19.0,0,0,112053,30.0000,B42,S
"Johnston, Miss. Catherine Helen ""Carrie""",0,3,female,NaN,1,2,W./C. 6607,23.4500,NaN,S
"Behr, Mr. Karl Howell",1,1,male,26.0,0,0,111369,30.0000,C148,C
"Dooley, Mr. Patrick",0,3,male,32.0,0,0,370376,7.7500,NaN,Q

In [75]:
df7 = df3[['Name','Survived','Pclass']][0:5]

KeyError: "None of [Index(['Name', 'Survived', 'Pclass'], dtype='object')] are in the [columns]"

In [76]:
# Use df instead of df3 as df contains the 'Name', 'Survived', and 'Pclass' columns
df7 = df[['Name','Survived','Pclass']][0:5]

KeyError: "['Name'] not in index"

In [77]:
# Use df instead of df3 as df contains the 'Name', 'Survived', and 'Pclass' columns
df7 = df[['Name','Survived','Pclass']][0:5]

KeyError: "['Name'] not in index"

In [73]:
df7

NameError: name 'df7' is not defined

pd.DataFrame(...): This calls the DataFrame constructor from the pandas library (which is imported as pd). This is the function used to create a DataFrame object.

In [78]:
data1 = pd.DataFrame({
    'key1': [1,2,4,5,6],
    'key2': [4,5,6,7,8],
    'key3': [3,4,5,6,6]
})

In [79]:
data1

   key1  key2  key3
0     1     4     3
1     2     5     4
2     4     6     5
3     5     7     6
4     6     8     6

In [84]:
data2 = pd.DataFrame({
    'key1':[1,2,45,5,67],
    'key4': [56,5,6,7,8],
    'key5': [3,56,5,6,6]
})

In [85]:
data2

   key1  key4  key5
0     1    56     3
1     2     5    56
2    45     6     5
3     5     7     6
4    67     8     6

In [86]:
#Merge data1 and data2
pd.merge(data1, data2) # By default inner merge: intersectionof data1 and data2

   key1  key2  key3  key4  key5
0     1     4     3    56     3
1     2     5     4     5    56
2     5     7     6     7     6

In [87]:
pd.merge(data1, data2, how='left') #Left merge: first all data come from data1 and then data2

   key1  key2  key3  key4  key5
0     1     4     3  56.0   3.0
1     2     5     4   5.0  56.0
2     4     6     5   NaN   NaN
3     5     7     6   7.0   6.0
4     6     8     6   NaN   NaN

In [88]:
pd.merge(data1, data2, how='right') #Right Merge: First data come from data2 and then data1

   key1  key2  key3  key4  key5
0     1   4.0   3.0    56     3
1     2   5.0   4.0     5    56
2    45   NaN   NaN     6     5
3     5   7.0   6.0     7     6
4    67   NaN   NaN     8     6

In [89]:
pd.merge(data1,data2, how='outer')

   key1  key2  key3  key4  key5
0     1   4.0   3.0  56.0   3.0
1     2   5.0   4.0   5.0  56.0
2     4   6.0   5.0   NaN   NaN
3     5   7.0   6.0   7.0   6.0
4     6   8.0   6.0   NaN   NaN
5    45   NaN   NaN   6.0   5.0
6    67   NaN   NaN   8.0   6.0

how='outer': This argument specifies the type of merge to perform. An outer merge includes all rows from both DataFrames, even if there are no matching values in the specified merge key(s). If a key exists in one DataFrame but not the other, the resulting row will have NaN (Not a Number) values for the columns from the DataFrame where the key was missing. This is similar to a SQL FULL OUTER JOIN [

In [90]:
pd.merge(data1, data2)

   key1  key2  key3  key4  key5
0     1     4     3    56     3
1     2     5     4     5    56
2     5     7     6     7     6

how='cross': This argument specifies the type of merge to perform. A cross merge creates all possible combinations of rows from the two DataFrames. For every row in the first DataFrame (data1), it is paired with every row in the second DataFrame (data2). The resulting DataFrame will have a number of rows equal to the product of the number of rows in data1 and the number of rows in data2. There is no matching of values between the DataFrames; it simply creates a combination of all rows from both sides.

In [91]:
pd.merge(data1, data2, how='cross')

    key1_x  key2  key3  key1_y  key4  key5
0        1     4     3       1    56     3
1        1     4     3       2     5    56
2        1     4     3      45     6     5
3        1     4     3       5     7     6
4        1     4     3      67     8     6
5        2     5     4       1    56     3
6        2     5     4       2     5    56
7        2     5     4      45     6     5
8        2     5     4       5     7     6
9        2     5     4      67     8     6
10       4     6     5       1    56     3
11       4     6     5       2     5    56
12       4     6     5      45     6     5
13       4     6     5       5     7     6
14       4     6     5      67     8     6
15       5     7     6       1    56     3
16       5     7     6       2     5    56
17       5     7     6      45     6     5
18       5     7     6       5     7     6
19       5     7     6      67     8     6
20       6     8     6       1    56     3
21       6     8     6       2     5    56
22       6     8     6      45     6     5
23       6     8     6       5     7     6
24       6     8     6      67     8     6

* left: use only keys from left frame, similar to a SQL left outer join;
  preserve key order.
* right: use only keys from right frame, similar to a SQL right outer join;
  preserve key order.
* outer: use union of keys from both frames, similar to a SQL full outer
  join; sort keys lexicographically.
* inner: use intersection of keys from both frames, similar to a SQL inner
  join; preserve the order of the left keys.
* cross: creates the cartesian product from both frames, preserves the order
  of the left keys.
  
  #shift + tab

In [92]:
pd.merge(data1, data2, how='outer', on='key1')

   key1  key2  key3  key4  key5
0     1   4.0   3.0  56.0   3.0
1     2   5.0   4.0   5.0  56.0
2     4   6.0   5.0   NaN   NaN
3     5   7.0   6.0   7.0   6.0
4     6   8.0   6.0   NaN   NaN
5    45   NaN   NaN   6.0   5.0
6    67   NaN   NaN   8.0   6.0